export TOKENIZERS_PARALLELISM=false
export MODEL_NAME="/root/autodl-tmp/StableAvatar/checkpoints/Wan2.1-Fun-V1.1-1.3B-InP"

CUDA_VISIBLE_DEVICES=0 uv run inference.py \
  --config_path="deepspeed_config/wan2.1/wan_civitai.yaml" \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --transformer_path="/root/autodl-tmp/StableAvatar/checkpoints/StableAvatar-1.3B/transformer3d-square.pt" \
  --pretrained_wav2vec_path="/root/autodl-tmp/StableAvatar/checkpoints/wav2vec2-base-960h" \
  --validation_reference_path="/root/autodl-tmp/StableAvatar/examples/case-1/reference.png" \
  --validation_driven_audio_path="/root/autodl-tmp/StableAvatar/examples/case-1/audio.wav" \
  --output_dir="/root/autodl-tmp/StableAvatar/output" \
  --validation_prompts="一位年轻的东亚女性，留着深色短发，坐在木桌旁，散发着一种平静平和的感觉。她面带微笑，目光平静，表情安详，说话的时候面部表情和肢体动作都非常非常地小，没有任何夸张的动作和表情，显得非常平静平和。" \
  --seed=42 \
  --ulysses_degree=1 \
  --ring_degree=1 \
  --motion_frame=25 \
  --sample_steps=50 \
  --width=512 \
  --height=512 \
  --overlap_window_length=15 \
  --clip_sample_n_frames=81 \
  --GPU_memory_mode="model_full_load" \
  --sample_text_guide_scale=3.0 \
  --sample_audio_guide_scale=5.0
