export TOKENIZERS_PARALLELISM=false
export MODEL_NAME="/root/autodl-tmp/StableAvatar/checkpoints/Wan2.1-Fun-V1.1-1.3B-InP"

CUDA_VISIBLE_DEVICES=0 uv run inference.py \
  --config_path="deepspeed_config/wan2.1/wan_civitai.yaml" \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --transformer_path="/root/autodl-tmp/StableAvatar/checkpoints/StableAvatar-1.3B/transformer3d-square.pt" \
  --pretrained_wav2vec_path="/root/autodl-tmp/StableAvatar/checkpoints/wav2vec2-base-960h" \
  --validation_reference_path="/root/autodl-tmp/StableAvatar/examples/case-1/reference.png" \
  --validation_driven_audio_path="/root/autodl-tmp/StableAvatar/examples/case-1/audio.wav" \
  --output_dir="/root/autodl-tmp/StableAvatar/output" \
  --validation_prompts="A young East Asian woman with short, dark hair, styled in a soft bob, framing her face in wavy curls, sits at a wooden table. She wears a comfortable, beige, long-sleeved sweater against a solid, pale blue background, radiating a sense of calm and serenity. She smiles, her gaze calm, her expression serene. As she speaks, her facial expressions and body movements are minimal, conveying a sense of calm and serenity." \
  --seed=42 \
  --ulysses_degree=1 \
  --ring_degree=1 \
  --motion_frame=25 \
  --sample_steps=50 \
  --width=512 \
  --height=512 \
  --overlap_window_length=5 \
  --clip_sample_n_frames=81 \
  --GPU_memory_mode="model_full_load" \
  --sample_text_guide_scale=3.0 \
  --sample_audio_guide_scale=5.0
